
version: '2.1'
konga:
    build: ./provisioning/dashboard/konga
    container_name: konga
    depends_on:
      konga-database:
        condition: service_healthy
    volumes:
      - ./provisioning/dashboard/konga/user_seed.js:/app/user_seed.js:ro
      - ${PWD}/.data/konga:/kongadata
    ports:
      - 1337:1337
    environment:
      DB_ADAPTER: postgres
      DB_DATABASE: kong
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      STORAGE_PATH: /kongadata
      KONGA_SEED_USER_DATA_SOURCE_FILE: /app/user_seed.js
      NODE_ENV: development
    restart: on-failure
    networks:
      - internal

