FROM kong:latest

# Kong install dir
ADD ./oidc-plugin/kong-oidc-auth /usr/local/share/lua/5.1/kong/plugins/kong-oidc-auth
RUN apk -U add --no-cache --virtual .build-deps git unzip gcc libc-dev openssl-dev
RUN (cd /usr/local/share/lua/5.1/kong/plugins/kong-oidc-auth && luarocks make *.rockspec)

